#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

python -m pytest -q
bash tests/c_host/run_host_test.sh
bash scripts/verify_patch.sh

python - <<'PY'
from pathlib import Path
import json, re, subprocess
root=Path(".")
# Ensure the patch is clean according to git's whitespace checker.
p=(root/"patches/0001-information-utility-scheduler.patch").read_text()
if "No newline at end of file" in p:
    raise SystemExit("patch contains an unterminated file")
subprocess.run(["git","apply","--check","--cached",str(root/"patches/0001-information-utility-scheduler.patch")],
               check=False, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
# Authored artifact must contain no model/AI attribution or watermark markers.
terms=re.compile(r"(?i)\\b(" + "|".join(["chat"+"gpt","open"+"ai","ai-generated","ai generated","generated by ai","watermark"]) + r")\\b")
hits=[]
for f in root.rglob("*"):
    if not f.is_file() or f.stat().st_size > 2_000_000:
        continue
    if any(part in {".git",".venv","build"} for part in f.parts):
        continue
    if f.name == "verify_release.sh":
        continue
    try:
        if terms.search(f.read_text(errors="ignore")):
            hits.append(str(f))
    except UnicodeDecodeError:
        pass
if hits:
    raise SystemExit("forbidden attribution/watermark markers: "+", ".join(hits))
cfg=json.loads((root/"configs/stage1.json").read_text())
res=json.loads((root/"results/stage1.json").read_text())
assert cfg["seeds"] == res["seeds"]
assert cfg["regimes"] == res["regimes"]
assert cfg["policies"] == res["policies"]
print("release verification: PASS")
PY
